
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'deel_globepay'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'deel_globepay'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

tests:
  deel_globepay:
    warn_freshness_base_globepay_transactions:
      config:
        severity: warn

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  deel_globepay:
    +persist_docs:
      relation: true
      columns:
        true

    base:
      globepay:
    # base layer, where raw data gets cleanup and renamed
    # according to enterprise standards
        +materialized: table
        +schema: base_transaction_flow
        
        chargebacks:
          intermediate:
            +schema: intermediate_base
            
        transactions:
          intermediate:
            +schema: intermediate_base

    core:
      +materialized: table
      +schema: core_transactional
      # Business logic and heavy/complex transformation layer
      payment_management:
        intermediate:
          +schema: intermediate_core_transactional

seeds:
  deel_globepay:
    acceptance_report_raw: 
      +column_types:
        date_time: timestamp 